// ── FontAwesome icon definitions for subjects ────────────────────────────
// Icons use the "fa:" prefix to distinguish from Lucide icons.
// The name after "fa:" follows the camelCase convention used in
// @fortawesome/free-solid-svg-icons (e.g., "fa:flask" for faFlask).

import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faFlask,
  faDna,
  faAtom,
  faCalculator,
  faGlobe,
  faMountain,
  faMicroscope,
  faBrain,
  faSquareRootVariable,
  faChartLine,
  faChartPie,
  faChartBar,
  faBook,
  faBookOpen,
  faBookmark,
  faPen,
  faPenFancy,
  faFeather,
  faLanguage,
  faTheaterMasks,
  faFilm,
  faCamera,
  faMusic,
  faPalette,
  faPaintBrush,
  faPencilRuler,
  faRuler,
  faRulerCombined,
  faHardHat,
  faWrench,
  faScrewdriver,
  faCogs,
  faCar,
  faPlane,
  faRocket,
  faBuilding,
  faIndustry,
  faTools,
  faLaptop,
  faLaptopCode,
  faComputer,
  faServer,
  faDatabase,
  faCloud,
  faWifi,
  faShield,
  faLock,
  faKey,
  faRobot,
  faMicrochip,
  faCode,
  faTerminal,
  faBolt,
  faFire,
  faLeaf,
  faTree,
  faDroplet,
  faWind,
  faSun,
  faMoon,
  faStar,
  faHeart,
  faHeartPulse,
  faStethoscope,
  faPills,
  faAppleAlt,
  faUserMd,
  faTooth,
  faEye,
  faUserGraduate,
  faSchool,
  faBagShopping,
  faClipboardList,
  faLightbulb,
  faBullseye,
  faTrophy,
  faCompass,
  faMap,
  faMapPin,
  faClock,
  faCalendar,
  faCalendarCheck,
  faGraduationCap,
  faBriefcase,
  faHandshake,
  faWallet,
  faCoins,
  faScaleBalanced,
  faGavel,
  faUsers,
  faFlag,
  faNewspaper,
  faVoteYea,
  faLandmark,
  faStore,
  faBullhorn,
  faCameraRetro,
  faHeadphones,
  faGamepad,
  faChess,
  faChessKnight,
  faCertificate,
  faAward,
  faScroll,
  faHistory,
  faInfinity,
  faRobot as faAndroid,
  faComments,
  faCommentDots,
  faQuestionCircle,
  faSearch,
  faSitemap,
  faProjectDiagram,
  faLayerGroup,
  faBalanceScale,
  faDiceD6,
  faDragon,
  faHatWizard,
  faSkull,
  faFistRaised,
  faShieldAlt,
  faMagic,
  faDivide,
  faPercentage,
  faFingerprint,
  faUserTie,
  faChalkboardTeacher,
  faBusinessTime,
  faMoneyBillWave,
  faPiggyBank,
  faHandHoldingUsd,
  faGift,
  faGem,
  faCrown,
  faWalking,
  faRunning,
  faBicycle,
  faSwimmer,
} from "@fortawesome/free-solid-svg-icons";

// Map from icon name (without "fa:" prefix) to IconDefinition
export const FA_ICON_MAP: Record<string, IconDefinition> = {
  flask: faFlask,
  dna: faDna,
  atom: faAtom,
  calculator: faCalculator,
  globe: faGlobe,
  mountain: faMountain,
  microscope: faMicroscope,
  brain: faBrain,
  "square-root": faSquareRootVariable,
  "chart-line": faChartLine,
  "chart-pie": faChartPie,
  "chart-bar": faChartBar,
  book: faBook,
  "book-open": faBookOpen,
  bookmark: faBookmark,
  pen: faPen,
  "pen-fancy": faPenFancy,
  feather: faFeather,
  language: faLanguage,
  theater: faTheaterMasks,
  film: faFilm,
  camera: faCamera,
  music: faMusic,
  palette: faPalette,
  "paint-brush": faPaintBrush,
  "pencil-ruler": faPencilRuler,
  ruler: faRuler,
  "ruler-combined": faRulerCombined,
  "hard-hat": faHardHat,
  wrench: faWrench,
  screwdriver: faScrewdriver,
  cogs: faCogs,
  car: faCar,
  plane: faPlane,
  rocket: faRocket,
  building: faBuilding,
  industry: faIndustry,
  tools: faTools,
  laptop: faLaptop,
  "laptop-code": faLaptopCode,
  computer: faComputer,
  server: faServer,
  database: faDatabase,
  cloud: faCloud,
  wifi: faWifi,
  shield: faShield,
  lock: faLock,
  key: faKey,
  robot: faRobot,
  microchip: faMicrochip,
  code: faCode,
  terminal: faTerminal,
  bolt: faBolt,
  fire: faFire,
  leaf: faLeaf,
  tree: faTree,
  droplet: faDroplet,
  wind: faWind,
  sun: faSun,
  moon: faMoon,
  star: faStar,
  heart: faHeart,
  "heart-pulse": faHeartPulse,
  stethoscope: faStethoscope,
  pills: faPills,
  "apple-alt": faAppleAlt,
  "user-md": faUserMd,
  tooth: faTooth,
  eye: faEye,
  "user-graduate": faUserGraduate,
  school: faSchool,
  "bag-shopping": faBagShopping,
  "clipboard-list": faClipboardList,
  lightbulb: faLightbulb,
  bullseye: faBullseye,
  trophy: faTrophy,
  compass: faCompass,
  map: faMap,
  "map-pin": faMapPin,
  clock: faClock,
  calendar: faCalendar,
  "calendar-check": faCalendarCheck,
  "graduation-cap": faGraduationCap,
  briefcase: faBriefcase,
  handshake: faHandshake,
  wallet: faWallet,
  coins: faCoins,
  "scale-balanced": faScaleBalanced,
  gavel: faGavel,
  users: faUsers,
  flag: faFlag,
  newspaper: faNewspaper,
  "vote-yea": faVoteYea,
  landmark: faLandmark,
  store: faStore,
  bullhorn: faBullhorn,
  "camera-retro": faCameraRetro,
  headphones: faHeadphones,
  gamepad: faGamepad,
  chess: faChess,
  "chess-knight": faChessKnight,
  certificate: faCertificate,
  award: faAward,
  scroll: faScroll,
  history: faHistory,
  infinity: faInfinity,
  android: faAndroid,
  comments: faComments,
  "comment-dots": faCommentDots,
  "question-circle": faQuestionCircle,
  search: faSearch,
  sitemap: faSitemap,
  "chart-network": faSitemap,
  "project-diagram": faProjectDiagram,
  "layer-group": faLayerGroup,
  "balance-scale": faBalanceScale,
  "dice-d6": faDiceD6,
  dragon: faDragon,
  "hat-wizard": faHatWizard,
  skull: faSkull,
  "fist-raised": faFistRaised,
  "shield-alt": faShieldAlt,
  magic: faMagic,
  divide: faDivide,
  percentage: faPercentage,
  fingerprint: faFingerprint,
  "user-tie": faUserTie,
  "chalkboard-teacher": faChalkboardTeacher,
  "business-time": faBusinessTime,
  "money-bill-wave": faMoneyBillWave,
  "piggy-bank": faPiggyBank,
  "hand-holding-usd": faHandHoldingUsd,
  gift: faGift,
  gem: faGem,
  crown: faCrown,
  walking: faWalking,
  running: faRunning,
  bicycle: faBicycle,
  swimmer: faSwimmer,
};

// List of all FA icon names with the "fa:" prefix
export const FA_ICON_NAMES = Object.keys(FA_ICON_MAP).map((k) => `fa:${k}`);
