import { inngest } from "./client";
import { groq } from "@ai-sdk/groq";
import { generateText } from "ai";
import { getSupabaseAdmin } from "@/lib/supabase-server";

/** A single quiz question generated by the AI, before DB insertion. */
interface GeneratedQuiz {
  question: string;
  options: string[];
  answer: string;
  tags: string[];
  subject?: string;
  topic?: string;
  difficulty?: string;
  explanation?: string;
}

/** Catalog of existing subjects and topics used to scope AI-generated questions. */
interface SubjectTopicCatalog {
  subjects: { id: string; name: string }[];
  topics: { id: string; title: string; subjectName: string | null }[];
}

/**
 * Parse AI response text, stripping markdown fences if present, and
 * returning the quizzes array (in either direct or wrapped form).
 */
function parseJsonFromAi(text: string): { quizzes: GeneratedQuiz[] } {
  const trimmed = text.trim();
  const jsonMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/) ?? [
    null,
    trimmed,
  ];
  const payload = JSON.parse(jsonMatch[1] ?? trimmed) as
    | { quizzes: GeneratedQuiz[] }
    | GeneratedQuiz[];

  if (Array.isArray(payload)) {
    return { quizzes: payload };
  }

  return payload;
}

/**
 * Fetch the full text content of a material (text, link, or file) for AI
 * ingestion. Truncates to 8000 characters.
 */
async function getMaterialContent(materialId: string): Promise<string> {
  const admin = getSupabaseAdmin();
  const { data: material, error } = await admin
    .from("materials")
    .select("*")
    .eq("id", materialId)
    .single();

  if (error || !material) {
    throw new Error(`Material not found: ${materialId}`);
  }

  if (material.type === "text" && material.content) {
    return material.content.slice(0, 8000);
  }

  if (material.type === "link") {
    return `Link title: ${material.name}\nURL: ${material.url ?? "unknown"}`;
  }

  if (material.type === "file" && material.storage_path) {
    const { data: blob, error: downloadError } = await admin.storage
      .from("materials")
      .download(material.storage_path);

    if (downloadError || !blob) {
      return `File: ${material.name} (${material.mime_type ?? "unknown type"})`;
    }

    const mime = material.mime_type ?? "";
    const isTextLike =
      mime.startsWith("text/") ||
      mime === "application/json" ||
      material.name.endsWith(".md") ||
      material.name.endsWith(".txt");

    if (isTextLike) {
      const text = await blob.text();
      return text.slice(0, 8000);
    }

    return `File: ${material.name} (${material.mime_type ?? "unknown type"})`;
  }

  return material.name;
}

/**
 * Match a free-text value to one of the existing options, preferring exact
 * match then substring match. Returns null when no match is found.
 */
function matchToExisting(
  value: string | undefined,
  options: string[],
): string | null {
  if (!value?.trim() || options.length === 0) return null;

  const normalized = value.trim().toLowerCase();
  const exact = options.find((option) => option.toLowerCase() === normalized);
  if (exact) return exact;

  const partial = options.find(
    (option) =>
      option.toLowerCase().includes(normalized) ||
      normalized.includes(option.toLowerCase()),
  );
  return partial ?? null;
}

/**
 * Build the system prompt telling the AI which existing subject/topic names
 * to reuse (to keep generated questions scoped to the user's taxonomy).
 */
function buildSubjectTopicPrompt(catalog: SubjectTopicCatalog): string {
  if (catalog.subjects.length === 0) {
    return `No predefined subjects or topics exist for this user. Infer appropriate subject and topic names for each question.`;
  }

  const grouped = catalog.subjects
    .map((subject) => {
      const subjectTopics = catalog.topics
        .filter((topic) => topic.subjectName === subject.name)
        .map((topic) => topic.title);

      if (subjectTopics.length === 0) {
        return `- ${subject.name}`;
      }

      return `- ${subject.name}\n  ${subjectTopics.map((topic) => `- ${topic}`).join("\n  ")}`;
    })
    .join("\n");

  return `Use ONLY these existing subject and topic names (copy them exactly):
${grouped}

For each quiz question, pick the closest matching subject and topic from the list above. Do not invent new subject or topic names.`;
}

/**
 * Resolve the AI-generated subject/topic strings against the existing catalog,
 * falling back to inferred or single-candidate values when ambiguous.
 */
function resolveQuizSubjectTopic(
  quiz: GeneratedQuiz,
  catalog: SubjectTopicCatalog,
): { subject: string | null; topic: string | null } {
  if (catalog.subjects.length === 0) {
    return {
      subject: quiz.subject?.trim() || null,
      topic: quiz.topic?.trim() || null,
    };
  }

  const subjectNames = catalog.subjects.map((subject) => subject.name);
  let subject = matchToExisting(quiz.subject, subjectNames);

  const topicsForSubject = subject
    ? catalog.topics
        .filter((topic) => topic.subjectName === subject)
        .map((topic) => topic.title)
    : catalog.topics.map((topic) => topic.title);

  let topic = matchToExisting(quiz.topic, topicsForSubject);

  if (topic && !subject) {
    const matchedTopic = catalog.topics.find((item) => item.title === topic);
    subject = matchedTopic?.subjectName ?? null;
  }

  if (!subject && subjectNames.length === 1) {
    subject = subjectNames[0];
  }

  const resolvedTopicsForSubject = subject
    ? catalog.topics
        .filter((topic) => topic.subjectName === subject)
        .map((topic) => topic.title)
    : catalog.topics.map((topic) => topic.title);

  if (subject && !topic && resolvedTopicsForSubject.length === 1) {
    topic = resolvedTopicsForSubject[0];
  }

  return { subject, topic };
}

/**
 * Inngest function: generate AI content (description + tags) for a topic
 * triggered by the `topic/ai.generate` event.
 */
export const generateTopicContent = inngest.createFunction(
  {
    id: 'generate-topic-content',
    triggers: { event: 'topic/ai.generate' },
  },
  async ({ event, step }) => {
    const { topicId, title, subjectName } = event.data;

    const result = await step.run('generate-ai-content', async () => {
      const { text } = await generateText({
        model: groq('llama-3.3-70b-versatile'),
        prompt: `Generate learning content for a topic titled "${title}"${subjectName ? ` under the subject "${subjectName}"` : ''}.

Return a JSON object with exactly two fields:
- "description": a 1-2 sentence explanation of the concept
- "tags": an array of 3-5 relevant lowercase hyphenated tags

Example:
{
  "description": "A mechanism that allows neural networks to focus on different parts of the input sequence when making predictions.",
  "tags": ["deep-learning", "transformers", "neural-networks"]
}

Return ONLY valid JSON, no other text.`,
      });

      return JSON.parse(text) as { description: string; tags: string[] };
    });

    await step.run('update-topic', async () => {
      await getSupabaseAdmin()
        .from('topics')
        .update({
          description: result.description,
          tags: result.tags,
        })
        .eq('id', topicId);
    });

    return { topicId, description: result.description, tags: result.tags };
  },
);

/**
 * Inngest function: generate quiz questions from uploaded material content,
 * insert into question_sets + questions tables, and sync legacy quizzes.
 * Triggered by the `material/quiz.generate` event.
 */
export const generateQuizFromMaterial = inngest.createFunction(
  {
    id: "generate-quiz-from-material",
    triggers: { event: "material/quiz.generate" },
  },
  async ({ event, step }) => {
    const { materialId, materialName, userId, subjectTopicCatalog } =
      event.data as {
        materialId: string;
        materialName: string;
        userId: string;
        subjectTopicCatalog?: SubjectTopicCatalog;
      };

    const catalog: SubjectTopicCatalog = subjectTopicCatalog ?? {
      subjects: [],
      topics: [],
    };

    const materialContent = await step.run("fetch-material-content", async () =>
      getMaterialContent(materialId),
    );

    const subjectTopicInstructions = buildSubjectTopicPrompt(catalog);

    const generated = await step.run("generate-quiz-questions", async () => {
      const { text } = await generateText({
        model: groq("llama-3.3-70b-versatile"),
        prompt: `You are an educational quiz generator. Based on the following study material, create 10-15 multiple-choice quiz questions.

Material title: "${materialName}"
Material content:
"""
${materialContent}
"""

${subjectTopicInstructions}

Return a JSON object with a "quizzes" array. Each quiz item must have:
- "question": string
- "options": array of exactly 4 answer strings
- "answer": the correct option string (must exactly match one of the options)
- "tags": array of 2-4 lowercase hyphenated concept tags related to the question
- "subject": subject name string
- "topic": topic name string
- "difficulty": classify as "easy", "medium", or "hard"
- "explanation": a brief explanation of why the answer is correct

Example:
{
  "quizzes": [
    {
      "question": "What is Newton's second law?",
      "options": ["F = ma", "E = mc^2", "V = IR", "P = IV"],
      "answer": "F = ma",
      "tags": ["physics", "newton-laws", "force"],
      "subject": "Physics",
      "topic": "Mechanics",
      "difficulty": "easy",
      "explanation": "Newton's second law states that force equals mass times acceleration."
    }
  ]
}

Return ONLY valid JSON, no other text.`,
      });

      return parseJsonFromAi(text);
    });

    const quizzes: GeneratedQuiz[] = (generated.quizzes ?? [])
      .filter(
        (quiz) =>
          quiz.question &&
          Array.isArray(quiz.options) &&
          quiz.options.length === 4 &&
          quiz.answer &&
          quiz.options.includes(quiz.answer),
      )
      .slice(0, 15) as GeneratedQuiz[];

    if (quizzes.length === 0) {
      throw new Error("AI did not return valid quiz questions");
    }

    // Resolve topic_id for scoping
    let resolvedTopicId: string | null = null;
    if (catalog.topics.length > 0) {
      const firstQuiz = quizzes[0];
      const { topic } = resolveQuizSubjectTopic(firstQuiz, catalog);
      if (topic) {
        const matchedTopic = catalog.topics.find(
          (t) => t.title === topic || t.title.toLowerCase() === topic.toLowerCase(),
        );
        if (matchedTopic) {
          resolvedTopicId = matchedTopic.id;
        }
      }
    }

    const setTitle = `Quiz: ${materialName}`;

    const questionSetId = await step.run('insert-question-set', async () => {
      const { data, error } = await (getSupabaseAdmin() as any)
        .from('question_sets')
        .insert({
          user_id: userId,
          topic_id: resolvedTopicId,
          title: setTitle,
          question_count: quizzes.length,
          difficulty: 'mixed',
          material_id: materialId,
        })
        .select('id')
        .single();
      if (error) throw error;
      return data.id as string;
    });

    await step.run('insert-questions', async () => {
      const rows = quizzes.map((quiz, idx) => ({
        question_set_id: questionSetId,
        question: quiz.question,
        options: quiz.options,
        answer: quiz.answer,
        explanation: quiz.explanation ?? null,
        difficulty: ['easy', 'medium', 'hard'].includes(quiz.difficulty ?? '')
          ? quiz.difficulty
          : 'medium',
        tags: quiz.tags ?? [],
        order: idx,
      }));

      const { error } = await (getSupabaseAdmin() as any).from('questions').insert(rows);
      if (error) throw error;
    });

    // Backward compatibility: also insert into old quizzes table
    await step.run('insert-legacy-quizzes', async () => {
      const rows = quizzes.map((quiz) => {
        const { subject, topic } = resolveQuizSubjectTopic(quiz, catalog);
        return {
          question: quiz.question,
          options: quiz.options,
          answer: quiz.answer,
          tags: quiz.tags ?? [],
          subject,
          topic,
          material_id: materialId,
          created_by: userId,
        };
      });
      const { error: legacyError } = await getSupabaseAdmin().from('quizzes').insert(rows);
      if (legacyError) throw new Error(`legacy quizzes insert failed: ${legacyError.message}`);
    });

    return { materialId, count: quizzes.length, questionSetTitle: setTitle };
  },
);
