// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwlbjpjnyyjeggzgbxvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bGJqcGpueXlqZWdnemdieHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxOTYwNjYsImV4cCI6MjA4Nzc3MjA2Nn0.xJNm7zGH0grp9FiL8ZjCJX1IervgMy1mDrwqugfUqPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const storage =
  typeof window !== "undefined"
    ? localStorage
    : {
        getItem: () => null,
        setItem: () => {},
        removeItem: () => {},
      };

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  },
});